permalink: "/:title"
markdown: redcarpet
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      source_url: "https://github.com/codeunion/glossary.codeunion.io/blob/gh-pages/"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      source_url: "https://github.com/codeunion/glossary.codeunion.io/blob/gh-pages/_posts/2014-01-01-"
